#!/bin/bash

# this script prints out any weird chars found in the dataset
# "weird chars" are any out of the range 0-128 in ASCII
# it prints ASCII values and char (if possible)

# TODO: actually do this...

# ACTUALLY --> THIS SHOULD ALL BE IN THE README PROBABLY...
# once it reports a weird char it should tell whoever ran it to append them to clean_file
echo "Here are the weird chars: "
# Report weird chars
echo "Once you find a suitable replacement, add it to the clean_file by calling: "
echo "cat s/\weird_char/\replacement/g >> clean_file"
echo "from your command line."